const { createClient } = require('@supabase/supabase-js');
require('dotenv').config({ path: '../backend/.env' });

const supabase = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_ANON_KEY);

const wordsBatch1 = [
    // A
    { w: "Ability", pt: "Habilidade", pron: "a-bí-li-ti", ex: "He has the ability to learn fast.", tr: "Ele tem a habilidade de aprender rápido.", expron: "rí rés dã a-bí-li-ti tu lêrn fást." },
    { w: "Able", pt: "Capaz", pron: "êi-bol", ex: "Are you able to do this?", tr: "Você é capaz de fazer isso?", expron: "ár iú êi-bol tu dú dís?" },
    { w: "About", pt: "Sobre", pron: "a-báut", ex: "What is this book about?", tr: "Sobre o que é este livro?", expron: "uát is dís búk a-báut?" },
    { w: "Above", pt: "Acima", pron: "a-bâv", ex: "The sky is above us.", tr: "O céu está acima de nós.", expron: "dã scái is a-bâv âs." },
    { w: "Accept", pt: "Aceitar", pron: "ak-sépt", ex: "I accept your apology.", tr: "Eu aceito suas desculpas.", expron: "ai ak-sépt iór a-pó-lo-dji." },
    { w: "According", pt: "De acordo", pron: "a-cór-din", ex: "According to the news, it will rain.", tr: "De acordo com as notícias, vai chover.", expron: "a-cór-din tu dã niús, it uíl rêin." },
    { w: "Account", pt: "Conta", pron: "a-cáunt", ex: "I need to open a bank account.", tr: "Preciso abrir uma conta no banco.", expron: "ai níd tu ôu-pen a bénk a-cáunt." },
    { w: "Across", pt: "Através / Do outro lado", pron: "a-crós", ex: "He walked across the street.", tr: "Ele andou até o outro lado da rua.", expron: "rí uókt a-crós dã is-trít." },
    { w: "Act", pt: "Agir", pron: "éct", ex: "You need to act now.", tr: "Você precisa agir agora.", expron: "iú níd tu éct náu." },
    { w: "Action", pt: "Ação", pron: "éc-chôn", ex: "Time for action.", tr: "Hora de ação.", expron: "táim fór éc-chôn." },
    { w: "Activity", pt: "Atividade", pron: "ak-tí-vi-ti", ex: "Running is a good activity.", tr: "Correr é uma boa atividade.", expron: "râ-nin iz a gúd ak-tí-vi-ti." },
    { w: "Actually", pt: "Na verdade", pron: "éc-tchua-li", ex: "Actually, I don't like it.", tr: "Na verdade, eu não gosto disso.", expron: "éc-tchua-li, ai dônt láik ít." },
    { w: "Add", pt: "Adicionar", pron: "éd", ex: "Add some sugar to my coffee.", tr: "Adicione um pouco de açúcar ao meu café.", expron: "éd sâm chú-gar tu mái cófi." },
    { w: "Address", pt: "Endereço", pron: "a-drés", ex: "What is your address?", tr: "Qual é o seu endereço?", expron: "uát iz iór a-drés?" },
    { w: "Admit", pt: "Admitir", pron: "ad-mít", ex: "I admit I was wrong.", tr: "Admito que eu estava errado.", expron: "ai ad-mít ai uóz róng." },
    { w: "Adult", pt: "Adulto", pron: "a-dâut", ex: "You are an adult now.", tr: "Você é um adulto agora.", expron: "iú ár én a-dâut náu." },
    { w: "Affect", pt: "Afetar", pron: "a-féct", ex: "This will affect everyone.", tr: "Isso vai afetar todo mundo.", expron: "dís uíl a-féct é-vri-uân." },
    { w: "After", pt: "Depois", pron: "éf-ter", ex: "Call me after lunch.", tr: "Me ligue depois do almoço.", expron: "cól mí éf-ter lántch." },
    { w: "Again", pt: "Novamente", pron: "a-guén", ex: "Please do it again.", tr: "Por favor, faça de novo.", expron: "plíiz dú it a-guén." },
    { w: "Against", pt: "Contra", pron: "a-guénst", ex: "I am against this idea.", tr: "Sou contra esta ideia.", expron: "ai ém a-guénst dís ai-dí-a." },
    { w: "Age", pt: "Idade", pron: "êidj", ex: "What is your age?", tr: "Qual é a sua idade?", expron: "uát iz iór êidj?" },
    { w: "Agency", pt: "Agência", pron: "êi-djen-si", ex: "I called a travel agency.", tr: "Eu liguei para uma agência de viagens.", expron: "ai cóud a tré-vel êi-djen-si." },
    { w: "Agent", pt: "Agente", pron: "êi-djent", ex: "He is a secret agent.", tr: "Ele é um agente secreto.", expron: "rí iz a sí-cret êi-djent." },
    { w: "Ago", pt: "Atrás (tempo)", pron: "a-gôu", ex: "I saw her a minute ago.", tr: "Eu a vi um minuto atrás.", expron: "ai só rêr a mí-nût a-gôu." },
    { w: "Agree", pt: "Concordar", pron: "a-gríi", ex: "I agree with you.", tr: "Eu concordo com você.", expron: "ai a-gríi uíth iú." },
    { w: "Agreement", pt: "Acordo", pron: "a-gríi-ment", ex: "We signed the agreement.", tr: "Nós assinamos o acordo.", expron: "uí sáind dã a-gríi-ment." },
    { w: "Ahead", pt: "À frente", pron: "a-réd", ex: "Look ahead.", tr: "Olhe para frente.", expron: "lúk a-réd." },
    { w: "Air", pt: "Ar", pron: "ér", ex: "I need some fresh air.", tr: "Preciso de um pouco de ar fresco.", expron: "ai níd sâm fréch ér." },
    { w: "All", pt: "Tudo / Todos", pron: "ól", ex: "All is well.", tr: "Tudo está bem.", expron: "ól iz uél." },
    { w: "Allow", pt: "Permitir", pron: "a-láu", ex: "Please allow me to help.", tr: "Por favor, permita-me ajudar.", expron: "plíiz a-láu mí tu réup." },
    { w: "Almost", pt: "Quase", pron: "ól-môust", ex: "We are almost there.", tr: "Nós estamos quase lá.", expron: "uí ár ól-môust dër." },
    { w: "Alone", pt: "Sozinho", pron: "a-lôun", ex: "I am not alone.", tr: "Eu não estou sozinho.", expron: "ai ém nót a-lôun." },
    { w: "Along", pt: "Junto", pron: "a-lóng", ex: "Come along with me.", tr: "Venha junto comigo.", expron: "câm a-lóng uíth mí." },
    { w: "Already", pt: "Já", pron: "ól-ré-di", ex: "I already did it.", tr: "Eu já fiz isso.", expron: "ai ól-ré-di díd ít." },
    { w: "Also", pt: "Também", pron: "ól-sou", ex: "I also like pizza.", tr: "Eu também gosto de pizza.", expron: "ai ól-sou láik pítsa." },
    { w: "Although", pt: "Embora", pron: "ól-dôu", ex: "Although it was raining, we went out.", tr: "Embora estivesse chovendo, nós saímos.", expron: "ól-dôu it uóz rêi-nin, uí uént áut." },
    { w: "Among", pt: "Entre (muitos)", pron: "a-mông", ex: "He is among friends.", tr: "Ele está entre amigos.", expron: "rí is a-mông frénds." },
    { w: "Amount", pt: "Quantia", pron: "a-máunt", ex: "A large amount of money.", tr: "Uma grande quantia de dinheiro.", expron: "a lárj a-máunt óv mâ-ni." },
    { w: "Analysis", pt: "Análise", pron: "a-ná-li-sis", ex: "We need a deep analysis.", tr: "Precisamos de uma análise profunda.", expron: "uí níd a díip a-ná-li-sis." },
    { w: "Animal", pt: "Animal", pron: "é-ni-môu", ex: "The dog is a smart animal.", tr: "O cachorro é um animal inteligente.", expron: "dã dóg iz a smárt é-ni-môu." },
    { w: "Another", pt: "Outro(a)", pron: "a-nó-der", ex: "I need another cup.", tr: "Eu preciso de outro copo.", expron: "ai níd a-nó-der câp." },
    { w: "Answer", pt: "Resposta", pron: "én-ser", ex: "What is the answer?", tr: "Qual é a resposta?", expron: "uát iz dã én-ser?" },
    { w: "Any", pt: "Qualquer / Algum", pron: "é-ni", ex: "Do you have any questions?", tr: "Você tem alguma pergunta?", expron: "dú iú rév é-ni cués-tchions?" },
    { w: "Anyone", pt: "Alguém", pron: "é-ni-uân", ex: "Is anyone home?", tr: "Tem alguém em casa?", expron: "iz é-ni-uân rôum?" },
    { w: "Anything", pt: "Qualquer coisa", pron: "é-ni-thing", ex: "I will do anything.", tr: "Eu farei qualquer coisa.", expron: "ai uíl dú é-ni-thing." },
    { w: "Appear", pt: "Aparecer", pron: "a-píer", ex: "He will appear soon.", tr: "Ele vai aparecer em breve.", expron: "rí uíl a-píer sún." },
    { w: "Apply", pt: "Aplicar", pron: "a-plái", ex: "You should apply for this job.", tr: "Você deveria se candidatar a este emprego.", expron: "iú chúd a-plái fór dís djób." },
    { w: "Approach", pt: "Abordagem", pron: "a-prôutch", ex: "We need a new approach.", tr: "Nós precisamos de uma nova abordagem.", expron: "uí níd a niú a-prôutch." },
    { w: "Area", pt: "Área", pron: "é-ri-a", ex: "This area is dangerous.", tr: "Esta área é perigosa.", expron: "dís é-ri-a iz dên-djer-os." },
    { w: "Argue", pt: "Discutir", pron: "ár-guiu", ex: "Let's not argue.", tr: "Não vamos discutir.", expron: "léts nót ár-guiu." },
    { w: "Arm", pt: "Braço", pron: "árm", ex: "My arm hurts.", tr: "Meu braço dói.", expron: "mái árm rârts." },
    { w: "Around", pt: "Ao redor", pron: "a-ráund", ex: "Look around you.", tr: "Olhe ao seu redor.", expron: "lúk a-ráund iú." },
    { w: "Arrive", pt: "Chegar", pron: "a-ráiv", ex: "We will arrive tomorrow.", tr: "Nós chegaremos amanhã.", expron: "uí uíl a-ráiv tu-mó-rou." },
    { w: "Art", pt: "Arte", pron: "árt", ex: "I love modern art.", tr: "Eu amo arte moderna.", expron: "ai lóv mó-dern árt." },
    { w: "Article", pt: "Artigo", pron: "ár-ti-col", ex: "I read an interesting article.", tr: "Eu li um artigo interessante.", expron: "ai réd én ín-tres-ting ár-ti-col." },
    { w: "Artist", pt: "Artista", pron: "ár-tist", ex: "She is a talented artist.", tr: "Ela é uma artista talentosa.", expron: "chí is a té-len-ted ár-tist." },
    { w: "Ask", pt: "Perguntar", pron: "ésk", ex: "Ask me anything.", tr: "Me pergunte qualquer coisa.", expron: "ésk mí é-ni-thing." },
    { w: "Assume", pt: "Presumir", pron: "a-súm", ex: "I assume you are ready.", tr: "Presumo que você esteja pronto.", expron: "ai a-súm iú ár ré-di." },
    { w: "Attack", pt: "Atacar", pron: "a-téc", ex: "The dog tried to attack me.", tr: "O cachorro tentou me atacar.", expron: "dã dóg tráid tu a-téc mí." },
    { w: "Attention", pt: "Atenção", pron: "a-tên-chôn", ex: "Pay attention in class.", tr: "Preste atenção na aula.", expron: "pêi a-tên-chôn in clés." },
    { w: "Attorney", pt: "Advogado", pron: "a-tôr-ni", ex: "I need to call my attorney.", tr: "Preciso ligar para meu advogado.", expron: "ai níd tu cól mái a-tôr-ni." },
    { w: "Audience", pt: "Público", pron: "ó-di-ens", ex: "The audience clapped.", tr: "O público aplaudiu.", expron: "dã ó-di-ens clépd." },
    { w: "Author", pt: "Autor", pron: "ó-tor", ex: "Who is the author of this book?", tr: "Quem é o autor deste livro?", expron: "rú iz di ó-tor óv dís búk?" },
    { w: "Authority", pt: "Autoridade", pron: "a-thó-ri-ti", ex: "He has the authority.", tr: "Ele tem a autoridade.", expron: "rí rés di a-thó-ri-ti." },
    { w: "Available", pt: "Disponível", pron: "a-vêi-la-bol", ex: "Is this room available?", tr: "Este quarto está disponível?", expron: "iz dís rúm a-vêi-la-bol?" },
    { w: "Avoid", pt: "Evitar", pron: "a-vóid", ex: "Try to avoid sugar.", tr: "Tente evitar açúcar.", expron: "trái tu a-vóid chú-gar." },
    { w: "Away", pt: "Longe", pron: "a-uêi", ex: "Go away.", tr: "Vá embora.", expron: "gôu a-uêi." },
    
    // B
    { w: "Baby", pt: "Bebê", pron: "bêi-bi", ex: "The baby is sleeping.", tr: "O bebê está dormindo.", expron: "dã bêi-bi iz slíi-ping." },
    { w: "Back", pt: "De volta / Costas", pron: "béc", ex: "I will be back soon.", tr: "Estarei de volta em breve.", expron: "ai uíl bí béc sún." },
    { w: "Bad", pt: "Mau / Ruim", pron: "béd", ex: "That is a bad idea.", tr: "Essa é uma má ideia.", expron: "dét iz a béd ai-dí-a." },
    { w: "Bag", pt: "Bolsa", pron: "bég", ex: "Where is my bag?", tr: "Onde está minha bolsa?", expron: "uér is mái bég?" },
    { w: "Ball", pt: "Bola", pron: "ból", ex: "Kick the ball.", tr: "Chute a bola.", expron: "kíc dã ból." },
    { w: "Bank", pt: "Banco", pron: "bénk", ex: "I need to go to the bank.", tr: "Preciso ir ao banco.", expron: "ai níd tu gôu tu dã bénk." },
    { w: "Bar", pt: "Bar", pron: "bár", ex: "Let's go to the bar.", tr: "Vamos ao bar.", expron: "léts gôu tu dã bár." },
    { w: "Base", pt: "Base", pron: "bêis", ex: "This is a solid base.", tr: "Esta é uma base sólida.", expron: "dís iz a só-lid bêis." },
    { w: "Be", pt: "Ser / Estar", pron: "bí", ex: "I want to be happy.", tr: "Eu quero ser feliz.", expron: "ai uánt tu bí ré-pi." },
    { w: "Beat", pt: "Bater / Vencer", pron: "bíit", ex: "We can beat them.", tr: "Nós podemos vencê-los.", expron: "uí kén bíit dêm." },
    { w: "Beautiful", pt: "Bonito(a)", pron: "biú-ti-ful", ex: "She is very beautiful.", tr: "Ela é muito bonita.", expron: "chí is vé-ri biú-ti-ful." },
    { w: "Because", pt: "Porque", pron: "bi-cóz", ex: "I cried because it hurts.", tr: "Eu chorei porque dói.", expron: "ai cráid bi-cóz it rârts." },
    { w: "Become", pt: "Tornar-se", pron: "bi-câm", ex: "I want to become a doctor.", tr: "Eu quero me tornar um médico.", expron: "ai uánt tu bi-câm a dók-tor." },
    { w: "Bed", pt: "Cama", pron: "béd", ex: "I am going to bed.", tr: "Estou indo para a cama.", expron: "ai ém gôin tu béd." },
    { w: "Before", pt: "Antes", pron: "bi-fór", ex: "Call me before you leave.", tr: "Me ligue antes de sair.", expron: "cól mí bi-fór iú lív." },
    { w: "Begin", pt: "Começar", pron: "bi-guín", ex: "Let's begin the class.", tr: "Vamos começar a aula.", expron: "léts bi-guín dã clés." },
    { w: "Behavior", pt: "Comportamento", pron: "bi-rêi-vior", ex: "His behavior is strange.", tr: "O comportamento dele é estranho.", expron: "riz bi-rêi-vior iz istrêindj." },
    { w: "Behind", pt: "Atrás", pron: "bi-ráind", ex: "Look behind you.", tr: "Olhe para trás de você.", expron: "lúk bi-ráind iú." },
    { w: "Believe", pt: "Acreditar", pron: "bi-líiv", ex: "I believe in you.", tr: "Eu acredito em você.", expron: "ai bi-líiv in iú." },
    { w: "Benefit", pt: "Benefício", pron: "bé-ne-fit", ex: "This has many benefits.", tr: "Isso tem muitos benefícios.", expron: "dís rés mé-ni bé-ne-fits." },
    { w: "Best", pt: "Melhor", pron: "bést", ex: "You are the best.", tr: "Você é o melhor.", expron: "iú ár dã bést." },
    { w: "Better", pt: "Melhor (comparativo)", pron: "bé-ter", ex: "This is better than that.", tr: "Isso é melhor que aquilo.", expron: "dís iz bé-ter dên dét." },
    { w: "Between", pt: "Entre", pron: "bi-tuín", ex: "It is a secret between us.", tr: "É um segredo entre nós.", expron: "it iz a sí-cret bi-tuín âs." },
    { w: "Beyond", pt: "Além", pron: "bi-iónd", ex: "This is beyond my control.", tr: "Isso está além do meu controle.", expron: "dís iz bi-iónd mái con-trôu." },
    { w: "Big", pt: "Grande", pron: "bíg", ex: "He has a big car.", tr: "Ele tem um carro grande.", expron: "rí rés a bíg cár." },
    { w: "Bill", pt: "Conta / Fatura", pron: "bíu", ex: "Please pay the bill.", tr: "Por favor, pague a conta.", expron: "plíiz pêi dã bíu." },
    { w: "Billion", pt: "Bilhão", pron: "bí-liôn", ex: "A billion stars.", tr: "Um bilhão de estrelas.", expron: "a bí-liôn stárs." },
    { w: "Bit", pt: "Um pouco", pron: "bít", ex: "Just a little bit.", tr: "Apenas um pouquinho.", expron: "djâst a lí-tou bít." },
    { w: "Black", pt: "Preto", pron: "bléc", ex: "I love black coffee.", tr: "Eu amo café preto.", expron: "ai lóv bléc cófi." },
    { w: "Blood", pt: "Sangue", pron: "blâd", ex: "Blood is red.", tr: "O sangue é vermelho.", expron: "blâd iz réd." },
    { w: "Blue", pt: "Azul", pron: "blú", ex: "The sky is blue.", tr: "O céu é azul.", expron: "dã scái is blú." },
    { w: "Board", pt: "Quadro / Embarcar", pron: "bórd", ex: "Look at the board.", tr: "Olhe para o quadro.", expron: "lúk ét dã bórd." },
    { w: "Body", pt: "Corpo", pron: "bó-di", ex: "Listen to your body.", tr: "Ouça o seu corpo.", expron: "lí-sen tu iór bó-di." },
    { w: "Book", pt: "Livro", pron: "búk", ex: "I read a good book.", tr: "Eu li um bom livro.", expron: "ai réd a gúd búk." },
    { w: "Born", pt: "Nascer", pron: "bórn", ex: "I was born in Brazil.", tr: "Eu nasci no Brasil.", expron: "ai uóz bórn in bra-zíl." },
    { w: "Both", pt: "Ambos", pron: "bôuth", ex: "I like both of them.", tr: "Eu gosto de ambos.", expron: "ai láik bôuth óv dêm." },
    { w: "Box", pt: "Caixa", pron: "bóks", ex: "What is in the box?", tr: "O que tem na caixa?", expron: "uát iz in dã bóks?" },
    { w: "Boy", pt: "Garoto", pron: "bói", ex: "The boy is playing.", tr: "O garoto está brincando.", expron: "dã bói iz plêi-ing." },
    { w: "Break", pt: "Quebrar / Pausa", pron: "brêik", ex: "Let's take a break.", tr: "Vamos fazer uma pausa.", expron: "léts têic a brêik." },
    { w: "Bring", pt: "Trazer", pron: "bríng", ex: "Bring me water.", tr: "Traga-me água.", expron: "bríng mi uó-ter." },
    { w: "Brother", pt: "Irmão", pron: "bró-der", ex: "He is my brother.", tr: "Ele é meu irmão.", expron: "rí is mái bró-der." },
    { w: "Budget", pt: "Orçamento", pron: "bád-jet", ex: "We need a new budget.", tr: "Precisamos de um novo orçamento.", expron: "uí níd a niú bád-jet." },
    { w: "Build", pt: "Construir", pron: "bíuld", ex: "They build houses.", tr: "Eles constroem casas.", expron: "dêi bíuld ráu-zes." },
    { w: "Building", pt: "Prédio", pron: "bíul-ding", ex: "That is a tall building.", tr: "Aquele é um prédio alto.", expron: "dét iz a tól bíul-ding." },
    { w: "Business", pt: "Negócios", pron: "bíz-nes", ex: "Business is good.", tr: "Os negócios estão bons.", expron: "bíz-nes iz gúd." },
    { w: "But", pt: "Mas", pron: "bât", ex: "I like it, but it is expensive.", tr: "Eu gosto, mas é caro.", expron: "ai láik ít, bât it iz eks-pên-siv." },
    { w: "Buy", pt: "Comprar", pron: "bái", ex: "I want to buy a car.", tr: "Eu quero comprar um carro.", expron: "ai uánt tu bái a cár." },
    { w: "By", pt: "Por / Até", pron: "bái", ex: "Written by me.", tr: "Escrito por mim.", expron: "rí-ten bái mí." },
    
    // C
    { w: "Call", pt: "Chamar / Ligar", pron: "cól", ex: "Call me tomorrow.", tr: "Me ligue amanhã.", expron: "cól mí tu-mó-rou." },
    { w: "Camera", pt: "Câmera", pron: "ké-me-ra", ex: "Smile for the camera.", tr: "Sorria para a câmera.", expron: "smáil fór dã ké-me-ra." },
    { w: "Campaign", pt: "Campanha", pron: "kém-pêin", ex: "A new marketing campaign.", tr: "Uma nova campanha de marketing.", expron: "a niú már-ke-tin kém-pêin." },
    { w: "Can", pt: "Poder (verbo)", pron: "kén", ex: "I can do this.", tr: "Eu posso fazer isso.", expron: "ai kén dú dís." },
    { w: "Cancer", pt: "Câncer", pron: "kên-ser", ex: "He cured his cancer.", tr: "Ele curou seu câncer.", expron: "rí kiúrd riz kên-ser." },
    { w: "Candidate", pt: "Candidato", pron: "kén-di-deit", ex: "She is a good candidate.", tr: "Ela é uma boa candidata.", expron: "chí is a gúd kén-di-deit." },
    { w: "Capital", pt: "Capital", pron: "ké-pi-tou", ex: "Paris is the capital of France.", tr: "Paris é a capital da França.", expron: "pé-ris iz dã ké-pi-tou óv fréns." },
    { w: "Car", pt: "Carro", pron: "cár", ex: "I drive a fast car.", tr: "Eu dirijo um carro rápido.", expron: "ai dráiv a fást cár." },
    { w: "Card", pt: "Cartão", pron: "cárd", ex: "Pay with credit card.", tr: "Pague com cartão de crédito.", expron: "pêi uíth cré-dit cárd." },
    { w: "Care", pt: "Cuidado / Importar-se", pron: "kér", ex: "I don't care.", tr: "Eu não me importo.", expron: "ai dônt kér." },
    { w: "Career", pt: "Carreira", pron: "ca-ríer", ex: "He has a great career.", tr: "Ele tem uma ótima carreira.", expron: "rí rés a grêit ca-ríer." },
    { w: "Carry", pt: "Carregar", pron: "ké-ri", ex: "Can you carry this bag?", tr: "Você pode carregar esta bolsa?", expron: "kén iú ké-ri dís bég?" },
    { w: "Case", pt: "Caso", pron: "kêis", ex: "In that case, I will go.", tr: "Nesse caso, eu irei.", expron: "in dét kêis, ai uíl gôu." },
    { w: "Catch", pt: "Pegar", pron: "kétch", ex: "Catch the ball.", tr: "Pegue a bola.", expron: "kétch dã ból." },
    { w: "Cause", pt: "Causa / Causar", pron: "cóz", ex: "What is the cause?", tr: "Qual é a causa?", expron: "uát iz dã cóz?" },
    { w: "Cell", pt: "Célula / Celular", pron: "sél", ex: "Where is my cell phone?", tr: "Onde está meu celular?", expron: "uér is mái sél fôun?" },
    { w: "Center", pt: "Centro", pron: "sên-ter", ex: "Go to the city center.", tr: "Vá para o centro da cidade.", expron: "gôu tu dã sí-ti sên-ter." },
    { w: "Central", pt: "Central", pron: "sên-tral", ex: "Central Park is huge.", tr: "O Central Park é enorme.", expron: "sên-tral párk iz riúdj." },
    { w: "Century", pt: "Século", pron: "sên-tu-ri", ex: "We live in the 21st century.", tr: "Vivemos no século 21.", expron: "uí lív in dã tuên-ti fêrst sên-tu-ri." },
    { w: "Certain", pt: "Certo", pron: "sêr-ten", ex: "I am certain of this.", tr: "Eu tenho certeza disso.", expron: "ai ém sêr-ten óv dís." },
    { w: "Certainly", pt: "Certamente", pron: "sêr-ten-li", ex: "I will certainly help.", tr: "Eu certamente ajudarei.", expron: "ai uíl sêr-ten-li réup." },
    { w: "Chair", pt: "Cadeira", pron: "tchér", ex: "Sit on the chair.", tr: "Sente na cadeira.", expron: "sít ón dã tchér." },
    { w: "Challenge", pt: "Desafio", pron: "tché-lêndj", ex: "I love a good challenge.", tr: "Eu amo um bom desafio.", expron: "ai lóv a gúd tché-lêndj." },
    { w: "Chance", pt: "Chance", pron: "tchêns", ex: "Give me one more chance.", tr: "Me dê mais uma chance.", expron: "gív mi uân mór tchêns." },
    { w: "Change", pt: "Mudança", pron: "tchêindj", ex: "Change is good.", tr: "A mudança é boa.", expron: "tchêindj iz gúd." },
    { w: "Character", pt: "Personagem / Caráter", pron: "ké-rec-ter", ex: "He is a strong character.", tr: "Ele é um personagem forte.", expron: "rí is a stróng ké-rec-ter." },
    { w: "Charge", pt: "Cobrar / Carga", pron: "tchárj", ex: "How much do you charge?", tr: "Quanto você cobra?", expron: "ráu mâtch dú iú tchárj?" },
    { w: "Check", pt: "Checar", pron: "tchéc", ex: "Let me check the time.", tr: "Deixe-me checar a hora.", expron: "lét mí tchéc dã táim." },
    { w: "Child", pt: "Criança", pron: "tchái-old", ex: "The child is playing.", tr: "A criança está brincando.", expron: "dã tchái-old iz plêi-in." },
    { w: "Choice", pt: "Escolha", pron: "tchóis", ex: "It is your choice.", tr: "É a sua escolha.", expron: "it iz iór tchóis." },
    { w: "Choose", pt: "Escolher", pron: "tchúz", ex: "Choose your weapon.", tr: "Escolha sua arma.", expron: "tchúz iór ué-pon." },
    { w: "Church", pt: "Igreja", pron: "tchêrtch", ex: "We go to church on Sundays.", tr: "Nós vamos à igreja aos domingos.", expron: "uí gôu tu tchêrtch ón sân-deiz." },
    { w: "Citizen", pt: "Cidadão", pron: "sí-ti-zen", ex: "I am a citizen here.", tr: "Eu sou um cidadão aqui.", expron: "ai ém a sí-ti-zen rír." },
    { w: "City", pt: "Cidade", pron: "sí-ti", ex: "I love this city.", tr: "Eu amo esta cidade.", expron: "ai lóv dís sí-ti." },
    { w: "Civil", pt: "Civil", pron: "sí-viul", ex: "Civil rights.", tr: "Direitos civis.", expron: "sí-viul ráits." },
    { w: "Claim", pt: "Afirmar / Reclamar", pron: "clêim", ex: "They claim to know the truth.", tr: "Eles afirmam saber a verdade.", expron: "dêi clêim tu nôu dã trút." },
    { w: "Class", pt: "Classe / Aula", pron: "clés", ex: "I have class today.", tr: "Eu tenho aula hoje.", expron: "ai rév clés tu-dêi." }
];

async function seedBatch1() {
    console.log("Iniciando geração de MAIS palavras (Lote A-C)...");

    let payload = wordsBatch1.map(item => ({
        word: item.w,
        meaning: item.pt,
        pronunciation_pt: item.pron,
        level: "Master",
        category: "A-Z Fluency",
        letter: item.w.charAt(0).toUpperCase(),
        example_sentence: item.ex,
        example_translation: item.tr,
        example_pronunciation_pt: item.expron,
        difficulty: 2
    }));

    // Inserindo
    console.log(`Inserindo ${payload.length} palavras puras...`);
    const { error } = await supabase.from('words').upsert(payload, { onConflict: 'word' });
    
    if (error) {
        console.error("Erro:", error);
    } else {
        console.log("Lote A-C inserido com sucesso!");
    }
}

// seedBatch1();

module.exports = { wordsBatch1 };
